name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install OWASP ZAP
      run: |
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.12.0/ZAP_2_12_0_Linux.tar.gz
        tar -xzf ZAP_2_12_0_Linux.tar.gz
        mv ZAP_2_12_0 zap

    - name: Run OWASP ZAP Passive Scan
      run: |
        ./zap/zap.sh -daemon -config api.key=12345
        ./zap/zap-baseline.py -t http://your-application-url -r zap-report.html

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap-report.html
