name: ZAP Security Scan

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Install OWASP ZAP
      run: |
        wget https://github.com/zaproxy/zaproxy/releases/download/w2024-12-09/ZAP_WEEKLY_D-2024-12-09.zip
        unzip ZAP_WEEKLY_D-2024-12-09.zip -d zap
		
	- name: Verify ZAP Directory
      run: |
        ls -R zap

    - name: Download ZAP Full Scan Script
      run: |
        wget -P zap/ https://raw.githubusercontent.com/zaproxy/zaproxy/main/docker/zap-full-scan.py
        chmod +x zap/zap-full-scan.py

    - name: Grant Execute Permissions
      run: |
        chmod +x zap/ZAP_WEEKLY_D-2024-12-09/zap.sh || ls -R zap
        chmod +x zap/zap-full-scan.py

    - name: Start OWASP ZAP Daemon
      run: |
        ./zap/ZAP_WEEKLY_D-2024-12-09/zap.sh -daemon -config api.key=irmje6k7mttb7dlqmvfvoeqvij &
        sleep 10 # Allow ZAP to start properly

    - name: Run ZAP Automation Script
      run: |
        ./mvnw compile exec:java -Dexec.mainClass="ZapAutomation"

    - name: Upload ZAP Reports
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: target/zap-report.xml
