name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  owasp-zap-scan:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Download and extract OWASP ZAP
    - name: Download OWASP ZAP
      run: |
        wget https://github.com/zaproxy/zaproxy/releases/download/w2024-12-09/ZAP_WEEKLY_D-2024-12-09.zip -O zap.zip
        unzip zap.zip -d zap

    # 3. Start OWASP ZAP
    - name: Start OWASP ZAP
      run: |
        nohup bash zap/zap.sh -daemon -host 127.0.0.1 -port 8080 &

    # 4. Wait for ZAP to start
    - name: Wait for ZAP to start
      run: sleep 30
   
    - name: Download zap-baseline.py
      run: |
        wget https://raw.githubusercontent.com/zaproxy/zaproxy/main/docker/zap-baseline.py -P zap/
        chmod +x zap/zap-baseline.py

    # 5. Run a security scan
    - name: Run ZAP Baseline Scan
      run: |
        python3 zap/zap-baseline.py -t https://www.mrtesting.com -r zap-report.html

    # 6. Upload the scan report
    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap-report.html
