name: OWASP ZAP Scan with Java

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11' # Use the Java version your project requires

    - name: Download and Extract ZAP
      run: |
        wget https://github.com/zaproxy/zaproxy/releases/download/w2024-12-09/ZAP_WEEKLY_D-2024-12-09.zip
        unzip ZAP_WEEKLY_D-2024-12-09.zip -d zap

    - name: Start ZAP Daemon
      run: |
        ./zap/ZAP_WEEKLY_D-2024-12-09/zap.sh -daemon -config api.key=irmje6k7mttb7dlqmvfvoeqvij &
        sleep 15 # Wait for ZAP to initialize

    - name: Build and Run ZAP Java Scan
      run: |
        mvn clean install # Build your project
        ls -lh target # List the JAR files in the target directory

    - name: Run ZAP Java Scan
      run: |
        jar_file=$(ls target/*.jar | head -n 1)
        echo "Found JAR file: $jar_file"
        java -cp "$jar_file" ZapScan

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap_report.html
