name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

       # Download and extract OWASP ZAP
      - name: Download OWASP ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/w2024-12-09/ZAP_WEEKLY_D-2024-12-09.zip
          unzip zap.zip -d zap

      - name: Build Project
        run: mvn clean package

      - name: Run ZAP Integration
        run: java -jar target/your-app.jar
