name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download and Extract OWASP ZAP
        run: |
          curl -L -o zap.zip https://github.com/zaproxy/zaproxy/releases/download/w2024-12-09/ZAP_WEEKLY_D-2024-12-09.zip
          unzip zap.zip -d zap

      - name: Start ZAP and Run Quick Scan
        run: |
          ./zap/zap.sh -daemon -config api.disablekey=true &
          sleep 30
          ./zap/zap-cli -p 8080 quick-scan http://your-web-application-url

      - name: Generate and Upload Report
        run: |
          ./zap/zap-cli -p 8080 report -o zap_report.html -f html
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html

